// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game-server.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	game-server.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserResponse
	LoginRequest
	LoginResponse
	RegisterToChannelRequest
	RegisterToChannelResponse
	SendToChannelRequest
	SendToChannelResponse
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{0} }

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{1} }

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{2} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{3} }

type RegisterToChannelRequest struct {
	ChannelName string `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
}

func (m *RegisterToChannelRequest) Reset()         { *m = RegisterToChannelRequest{} }
func (m *RegisterToChannelRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterToChannelRequest) ProtoMessage()    {}
func (*RegisterToChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorGameServer, []int{4}
}

func (m *RegisterToChannelRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type RegisterToChannelResponse struct {
}

func (m *RegisterToChannelResponse) Reset()         { *m = RegisterToChannelResponse{} }
func (m *RegisterToChannelResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterToChannelResponse) ProtoMessage()    {}
func (*RegisterToChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorGameServer, []int{5}
}

type SendToChannelRequest struct {
	ChannelName string `protobuf:"bytes,1,opt,name=channelName,proto3" json:"channelName,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *SendToChannelRequest) Reset()                    { *m = SendToChannelRequest{} }
func (m *SendToChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*SendToChannelRequest) ProtoMessage()               {}
func (*SendToChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{6} }

func (m *SendToChannelRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *SendToChannelRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SendToChannelRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendToChannelResponse struct {
}

func (m *SendToChannelResponse) Reset()                    { *m = SendToChannelResponse{} }
func (m *SendToChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*SendToChannelResponse) ProtoMessage()               {}
func (*SendToChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptorGameServer, []int{7} }

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "pb.CreateUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*RegisterToChannelRequest)(nil), "pb.RegisterToChannelRequest")
	proto.RegisterType((*RegisterToChannelResponse)(nil), "pb.RegisterToChannelResponse")
	proto.RegisterType((*SendToChannelRequest)(nil), "pb.SendToChannelRequest")
	proto.RegisterType((*SendToChannelResponse)(nil), "pb.SendToChannelResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameServer service

type GameServerClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterToChannel(ctx context.Context, in *RegisterToChannelRequest, opts ...grpc.CallOption) (GameServer_RegisterToChannelClient, error)
	SendToChannel(ctx context.Context, in *SendToChannelRequest, opts ...grpc.CallOption) (*SendToChannelResponse, error)
}

type gameServerClient struct {
	cc *grpc.ClientConn
}

func NewGameServerClient(cc *grpc.ClientConn) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/pb.GameServer/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/pb.GameServer/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServerClient) RegisterToChannel(ctx context.Context, in *RegisterToChannelRequest, opts ...grpc.CallOption) (GameServer_RegisterToChannelClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameServer_serviceDesc.Streams[0], c.cc, "/pb.GameServer/RegisterToChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServerRegisterToChannelClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameServer_RegisterToChannelClient interface {
	Recv() (*RegisterToChannelResponse, error)
	grpc.ClientStream
}

type gameServerRegisterToChannelClient struct {
	grpc.ClientStream
}

func (x *gameServerRegisterToChannelClient) Recv() (*RegisterToChannelResponse, error) {
	m := new(RegisterToChannelResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameServerClient) SendToChannel(ctx context.Context, in *SendToChannelRequest, opts ...grpc.CallOption) (*SendToChannelResponse, error) {
	out := new(SendToChannelResponse)
	err := grpc.Invoke(ctx, "/pb.GameServer/SendToChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameServer service

type GameServerServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RegisterToChannel(*RegisterToChannelRequest, GameServer_RegisterToChannelServer) error
	SendToChannel(context.Context, *SendToChannelRequest) (*SendToChannelResponse, error)
}

func RegisterGameServerServer(s *grpc.Server, srv GameServerServer) {
	s.RegisterService(&_GameServer_serviceDesc, srv)
}

func _GameServer_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameServer/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameServer/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameServer_RegisterToChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterToChannelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServerServer).RegisterToChannel(m, &gameServerRegisterToChannelServer{stream})
}

type GameServer_RegisterToChannelServer interface {
	Send(*RegisterToChannelResponse) error
	grpc.ServerStream
}

type gameServerRegisterToChannelServer struct {
	grpc.ServerStream
}

func (x *gameServerRegisterToChannelServer) Send(m *RegisterToChannelResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GameServer_SendToChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServerServer).SendToChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GameServer/SendToChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServerServer).SendToChannel(ctx, req.(*SendToChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _GameServer_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GameServer_Login_Handler,
		},
		{
			MethodName: "SendToChannel",
			Handler:    _GameServer_SendToChannel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterToChannel",
			Handler:       _GameServer_RegisterToChannel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game-server.proto",
}

func init() { proto.RegisterFile("game-server.proto", fileDescriptorGameServer) }

var fileDescriptorGameServer = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4e, 0xc3, 0x30,
	0x0c, 0xc7, 0x59, 0x11, 0x5f, 0x86, 0x09, 0x6a, 0x6d, 0x90, 0x15, 0x90, 0xa6, 0x9e, 0xb8, 0x50,
	0x21, 0xb8, 0xc2, 0x69, 0xd2, 0x38, 0x80, 0x38, 0x74, 0xe3, 0x01, 0x52, 0x66, 0x95, 0x49, 0x2c,
	0x09, 0x49, 0x07, 0xcf, 0xc2, 0xdb, 0xd2, 0xaf, 0x6c, 0x5d, 0xd7, 0x1d, 0x10, 0x47, 0xfb, 0x6f,
	0xff, 0x1c, 0xff, 0x1d, 0x70, 0x63, 0x3e, 0xa3, 0x6b, 0x43, 0xfa, 0x8b, 0x74, 0xa0, 0xb4, 0x4c,
	0x24, 0x3a, 0x2a, 0xf2, 0x9f, 0xc0, 0x1d, 0x68, 0xe2, 0x09, 0xbd, 0xa6, 0x52, 0x48, 0x9f, 0x73,
	0x32, 0x09, 0x7a, 0xb0, 0x3f, 0x4f, 0x43, 0x91, 0x76, 0xb0, 0x56, 0xbf, 0x75, 0x75, 0x10, 0x2e,
	0xe2, 0x4c, 0x53, 0xdc, 0x98, 0x6f, 0xa9, 0x27, 0xcc, 0x29, 0x34, 0x1b, 0xfb, 0x1d, 0xc0, 0x2a,
	0xcc, 0x28, 0x29, 0x0c, 0xf9, 0x43, 0x38, 0x7a, 0x96, 0xf1, 0x54, 0xfc, 0x97, 0x7e, 0x0c, 0xed,
	0x92, 0x53, 0x82, 0xef, 0x81, 0x85, 0x14, 0x4f, 0x4d, 0x42, 0x7a, 0x2c, 0x07, 0xef, 0x5c, 0x08,
	0xfa, 0xb0, 0x43, 0xfa, 0x70, 0xf8, 0x56, 0x64, 0x5e, 0x96, 0x73, 0xaa, 0x29, 0xff, 0x1c, 0x7a,
	0x0d, 0xdd, 0x25, 0x5a, 0x40, 0x67, 0x44, 0x62, 0xf2, 0x77, 0xec, 0xca, 0x76, 0x4e, 0x6d, 0x3b,
	0x06, 0x7b, 0x33, 0x32, 0x86, 0xc7, 0xc4, 0xb6, 0x73, 0xc9, 0x86, 0xfe, 0x19, 0x74, 0x6b, 0xf3,
	0x8a, 0x87, 0xdc, 0xfe, 0x38, 0x00, 0x8f, 0x69, 0xef, 0x28, 0x3f, 0x1c, 0x3e, 0x00, 0x2c, 0x1d,
	0xc6, 0x6e, 0xa0, 0xa2, 0x60, 0xed, 0x7c, 0xde, 0x69, 0x3d, 0x5d, 0x2e, 0xb5, 0x85, 0x01, 0xec,
	0xe4, 0x16, 0xe2, 0x49, 0x56, 0x52, 0xbd, 0x8a, 0xe7, 0x56, 0x32, 0x8b, 0xfa, 0x31, 0xb8, 0x6b,
	0x1e, 0xe1, 0x45, 0x56, 0xb9, 0xc9, 0x78, 0xef, 0x72, 0x83, 0x6a, 0x99, 0x37, 0x2d, 0x1c, 0x42,
	0x7b, 0x65, 0x59, 0x64, 0x59, 0x4f, 0x93, 0xdf, 0x5e, 0xaf, 0x41, 0xb1, 0xa4, 0x68, 0x37, 0xff,
	0xc6, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xd4, 0x78, 0xe1, 0xdb, 0x02, 0x00, 0x00,
}
